//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElevenAlpha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> Timeslot { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Member Member { get; set; }
    }
}
